name: Test documentation
on:
  workflow_call:
  pull_request:
    paths:
      - "docs/**"
jobs:
  test-deploy:
    name: Test doc deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./docs
      - name: Test build website
        run: yarn build
        working-directory: ./docs
